// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: src/schemas/hello.proto

package schemas

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=Host,proto3" json:"Host,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	PublicIP      string                 `protobuf:"bytes,4,opt,name=PublicIP,proto3" json:"PublicIP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloMsg) Reset() {
	*x = HelloMsg{}
	mi := &file_src_schemas_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloMsg) ProtoMessage() {}

func (x *HelloMsg) ProtoReflect() protoreflect.Message {
	mi := &file_src_schemas_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloMsg.ProtoReflect.Descriptor instead.
func (*HelloMsg) Descriptor() ([]byte, []int) {
	return file_src_schemas_hello_proto_rawDescGZIP(), []int{0}
}

func (x *HelloMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloMsg) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *HelloMsg) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *HelloMsg) GetPublicIP() string {
	if x != nil {
		return x.PublicIP
	}
	return ""
}

var File_src_schemas_hello_proto protoreflect.FileDescriptor

const file_src_schemas_hello_proto_rawDesc = "" +
	"\n" +
	"\x17src/schemas/hello.proto\x12\aschemas\"h\n" +
	"\bHelloMsg\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Host\x18\x02 \x01(\tR\x04Host\x12\x18\n" +
	"\aAddress\x18\x03 \x01(\tR\aAddress\x12\x1a\n" +
	"\bPublicIP\x18\x04 \x01(\tR\bPublicIPB8Z6github.com/Bastien-Antigravity/safe-socket/src/schemasb\x06proto3"

var (
	file_src_schemas_hello_proto_rawDescOnce sync.Once
	file_src_schemas_hello_proto_rawDescData []byte
)

func file_src_schemas_hello_proto_rawDescGZIP() []byte {
	file_src_schemas_hello_proto_rawDescOnce.Do(func() {
		file_src_schemas_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_schemas_hello_proto_rawDesc), len(file_src_schemas_hello_proto_rawDesc)))
	})
	return file_src_schemas_hello_proto_rawDescData
}

var file_src_schemas_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_schemas_hello_proto_goTypes = []any{
	(*HelloMsg)(nil), // 0: schemas.HelloMsg
}
var file_src_schemas_hello_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_schemas_hello_proto_init() }
func file_src_schemas_hello_proto_init() {
	if File_src_schemas_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_schemas_hello_proto_rawDesc), len(file_src_schemas_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_schemas_hello_proto_goTypes,
		DependencyIndexes: file_src_schemas_hello_proto_depIdxs,
		MessageInfos:      file_src_schemas_hello_proto_msgTypes,
	}.Build()
	File_src_schemas_hello_proto = out.File
	file_src_schemas_hello_proto_goTypes = nil
	file_src_schemas_hello_proto_depIdxs = nil
}
