// Code generated by capnpc-go. DO NOT EDIT.

package schemas

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type HelloMsg capnp.Struct

// HelloMsg_TypeID is the unique identifier for the type HelloMsg.
const HelloMsg_TypeID = 0xda3c8f277bce810b

func NewHelloMsg(s *capnp.Segment) (HelloMsg, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return HelloMsg(st), err
}

func NewRootHelloMsg(s *capnp.Segment) (HelloMsg, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return HelloMsg(st), err
}

func ReadRootHelloMsg(msg *capnp.Message) (HelloMsg, error) {
	root, err := msg.Root()
	return HelloMsg(root.Struct()), err
}

func (s HelloMsg) String() string {
	str, _ := text.Marshal(0xda3c8f277bce810b, capnp.Struct(s))
	return str
}

func (s HelloMsg) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (HelloMsg) DecodeFromPtr(p capnp.Ptr) HelloMsg {
	return HelloMsg(capnp.Struct{}.DecodeFromPtr(p))
}

func (s HelloMsg) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s HelloMsg) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s HelloMsg) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s HelloMsg) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s HelloMsg) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s HelloMsg) HasName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s HelloMsg) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s HelloMsg) SetName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s HelloMsg) Host() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s HelloMsg) HasHost() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s HelloMsg) HostBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s HelloMsg) SetHost(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s HelloMsg) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s HelloMsg) HasAddress() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s HelloMsg) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s HelloMsg) SetAddress(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s HelloMsg) PublicIP() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s HelloMsg) HasPublicIP() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s HelloMsg) PublicIPBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s HelloMsg) SetPublicIP(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// HelloMsg_List is a list of HelloMsg.
type HelloMsg_List = capnp.StructList[HelloMsg]

// NewHelloMsg creates a new list of HelloMsg.
func NewHelloMsg_List(s *capnp.Segment, sz int32) (HelloMsg_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[HelloMsg](l), err
}

// HelloMsg_Future is a wrapper for a HelloMsg promised by a client call.
type HelloMsg_Future struct{ *capnp.Future }

func (f HelloMsg_Future) Struct() (HelloMsg, error) {
	p, err := f.Future.Ptr()
	return HelloMsg(p.Struct()), err
}

type PacketEnvelope capnp.Struct

// PacketEnvelope_TypeID is the unique identifier for the type PacketEnvelope.
const PacketEnvelope_TypeID = 0xcc0f564ba623e267

func NewPacketEnvelope(s *capnp.Segment) (PacketEnvelope, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PacketEnvelope(st), err
}

func NewRootPacketEnvelope(s *capnp.Segment) (PacketEnvelope, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return PacketEnvelope(st), err
}

func ReadRootPacketEnvelope(msg *capnp.Message) (PacketEnvelope, error) {
	root, err := msg.Root()
	return PacketEnvelope(root.Struct()), err
}

func (s PacketEnvelope) String() string {
	str, _ := text.Marshal(0xcc0f564ba623e267, capnp.Struct(s))
	return str
}

func (s PacketEnvelope) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (PacketEnvelope) DecodeFromPtr(p capnp.Ptr) PacketEnvelope {
	return PacketEnvelope(capnp.Struct{}.DecodeFromPtr(p))
}

func (s PacketEnvelope) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s PacketEnvelope) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s PacketEnvelope) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s PacketEnvelope) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s PacketEnvelope) SenderID() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s PacketEnvelope) HasSenderID() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s PacketEnvelope) SenderIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s PacketEnvelope) SetSenderID(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s PacketEnvelope) Payload() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s PacketEnvelope) HasPayload() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s PacketEnvelope) SetPayload(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// PacketEnvelope_List is a list of PacketEnvelope.
type PacketEnvelope_List = capnp.StructList[PacketEnvelope]

// NewPacketEnvelope creates a new list of PacketEnvelope.
func NewPacketEnvelope_List(s *capnp.Segment, sz int32) (PacketEnvelope_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[PacketEnvelope](l), err
}

// PacketEnvelope_Future is a wrapper for a PacketEnvelope promised by a client call.
type PacketEnvelope_Future struct{ *capnp.Future }

func (f PacketEnvelope_Future) Struct() (PacketEnvelope, error) {
	p, err := f.Future.Ptr()
	return PacketEnvelope(p.Struct()), err
}

const schema_cf4762d38e91a0b1 = "x\xdal\x8f\xbdJ#Q\x18\x86\xdf\xf7\x9c\xc9\xce\xc2" +
	"&$C\x02\xbb\xb0\xddn\xb1?\xa8!h!b!" +
	"\xa2h\x14!\xc7\xc2\xca\xc2\x93\x99C\x12\x9c?s\xe2" +
	"\x1f\x16\xe2\x0d(\xde\x81\x95\xbdx\x1b\xa2\x85\x9d\xa5\x8d" +
	"\xb5W02BB\x10\xcb\xef\xe5\x81\xe7\xf9*\xb7\x0b" +
	"N\xa3\xf4]@\xa8\x1f\x85/Y\xe7\xf9\xf7\xf5\xfaV" +
	"\xf9\x0e\xdeOf7W\x97\xe7\x8f\xed\x95\x07\x14\x84\x0b" +
	"4^7Y-\xd0\x05\xaa\xe4!\x98};\xbb?\xf9" +
	"s1\xff\xf4\x81u\\`Z\xf3\x17\xab{\xefp\xc4" +
	"\x17Lf\xb6\xef\xd7\xad\xdf5N\xa4m=2\xd6\xea" +
	"\x8e\xb1S\xbeN\xe3t\xae\xa5\xfd]3X\x8e\x0fL" +
	"\x98\xa44-R}\x95\x0e\xe0\x10\xf0\xfe\xad\x01\xea\xaf" +
	"\xa4\x9a\x11\xf4\xc8\x1a\xf3\xb1\xb1\x08\xa8\x09I5+\x98" +
	"Y\x13\x07\xa6\xdf\\\x02\xc0\"\x04\x8b\xe0i\xaa\x8f\xc3" +
	"D\x07,A\xb0\x04\x8e\xf4\xf2\x13\xfd\xaa\x09\xc3\xc4\xdd" +
	"\xb0\x9d\\\\\x19\x89\xf5\x7f@mK\xaa\xee\x98\xd8\xe4" +
	"\xe3\x8e\xa4\x0a\x05=!j\x14\x80\xd7\xcbk\x02I\x95" +
	"\x0azR\xd6(\x01/\xca\xbbCIu$X\x8eu" +
	"d\x86m\xe5nb\x07\xa3P\x1d\x04}c\xed\xf0\xce" +
	"\xd2\xfdv\xd8\xf3\x9b\xad\xb1g\xde\x02\x00\x00\xff\xffY" +
	"\xfe\\g"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_cf4762d38e91a0b1,
		Nodes: []uint64{
			0xcc0f564ba623e267,
			0xda3c8f277bce810b,
		},
		Compressed: true,
	})
}
